### ISSUE TITLE
Cleanup google share model

### ISSUE THREAD

**Issue by Billflorio** [SFDO-Community-Sprints/NPSP-Videography#79]
All down to base group

**Comment by barbarachristensen** [comment]
This is done
@charise @Billflorio all scripts since github should now live here: The link is publicly viewable, but we have to grant access as needed to edit scripts:
https://drive.google.com/drive/folders/1t1tC_EtsjUdLMO2YE-O4w_-oV8-xsbeh?usp=sharing

all the old script structure kept in sync by me w/ the process are in the archive folder and mostly unviewable/uneditable, except docs owned by original writer. We should maybe copy those logged in as NPSP Vid, so that is the final owner, just in case an original writer/owner deletes (or goes rogue ;p)

**Comment by barbarachristensen** [comment]
The template model maybe isn't enough-- can we automate this some way via a slack WF tied to a sheet or just straight to git
- add their user to the git repo?
- assign them to a sprint subfolder in the main docs flder or the main docs folder
