### ISSUE TITLE
Advanced Mapping: Enable & Convert to Advanced Mapping

### ISSUE THREAD

**Issue by Billflorio** [SFDO-Community-Sprints/NPSP-Videography#85]
Super quick how to turn on AM. This is the info on doing the mapping: #81 

https://powerofus.force.com/s/article/NPSP-Enable-Convert-Advanced-Mapping#ariaid-title2

https://docs.google.com/document/d/1cCGTlVmfKIv_BFGNM8A7oewHXMK4CWz7Z-OKdj1iTn0/edit?usp=sharing

**Comment by melissabarber** [comment]
@Billflorio instead of combining this with setting up the mapping (#81), how about adjusting this script to be more:

1. Intro about AM (https://powerofus.force.com/s/article/NPSP-Advanced-Mapping-Overview)
2. Enabling AM (https://powerofus.force.com/s/article/NPSP-Enable-Convert-Advanced-Mapping)
3. When to Customize Advanced Mapping (https://powerofus.force.com/s/article/NPSP-Map-Using-Advanced-Mapping#ariaid-title2).
4. Lead into the next video about customizing AM.
